# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Check formatting with black
        run: |
          black improv_ble_client --check --diff
      - name: Lint with flake8
        run: |
          flake8 improv_ble_client
      - name: Lint with isort
        run: |
          isort improv_ble_client
      - name: Lint with mypy
        run: |
          mypy improv_ble_client
      - name: Lint with pylint
        run: |
          pylint improv_ble_client
